###
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "admin3",
    "email": "admin3@admin.ru"
}
###
POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "admin3",
    "confirmation_code": "FIIQWdemi1QiHDp9tDDqme9leTgSBAOOQk555ztPwZ8qJdwo58DBGMykUfTybndj"
}
###
