###
GET http://127.0.0.1:8000/api/v1/categories/
###
GET http://127.0.0.1:8000/api/v1/genres/
###
GET http://127.0.0.1:8000/api/v1/titles/
###
GET http://127.0.0.1:8000/api/v1/titles/1/reviews/
###
GET http://127.0.0.1:8000/api/v1/titles/1/reviews/6/comments/
###
GET http://127.0.0.1:8000/api/v1/titles/100500/reviews/6/comments/
###
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "admin3",
    "email": "admin3@admin.ru"
}
###
POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "admin3",
    "confirmation_code": "MdgdrEG993S8KNeQHPy9ei0yYsoCTD1ZY4Bhij6wz9cGY9b0vdlFlNgAzmPdcLzC"
}
###
POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "admin5",
    "confirmation_code": "RipKMFoAp4gnB07Ab1D8PSYXDVgm5A4GhIPZc1l1NorQTUuGRjrLZMRR7o9J31YF"
}
###
GET http://127.0.0.1:8000/api/v1/categories/
###
POST http://127.0.0.1:8000/api/v1/categories/
Content-Type: application/json

{
    "name": "Программирование",
    "slug": "programme"
}
###
#  admin3 ---> role admin:
###
POST http://127.0.0.1:8000/api/v1/categories/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzY1NjczLCJpYXQiOjE2NzIxNTYwNzMsImp0aSI6IjNmNTAzYzYzNDgzMTRjMzhiNzJiNzg1ZTBkMTQ4Yzc2IiwidXNlcl9pZCI6MTA5fQ.CKuUL6AN-wLFMucfEaGVH-TX-audRwAr7vX1ZPUZAZE
Content-Type: application/json

{
    "name": "Программирование",
    "slug": "programme"
}

###
# Приложение Users:
# + admin3 ---> role admin
GET http://127.0.0.1:8000/api/v1/users/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzI5ODg5LCJpYXQiOjE2NzIxMjAyODksImp0aSI6IjM5YjQzZTVhZjQ0OTQ3ZGJhOWZjOWNlNDg3ZTFlM2QzIiwidXNlcl9pZCI6MX0.RpJ5EbY0_vkj-09qFYVx-CCkyJT0k-TWwjOjhyP0Brc
###
# + admin5 ---> role user
GET http://127.0.0.1:8000/api/v1/users/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzcxNTQ5LCJpYXQiOjE2NzIxNjE5NDksImp0aSI6IjI4N2RhMDFiOWY2NzRiMDZhM2U5NDRmZTQxZDkwMjI4IiwidXNlcl9pZCI6MTA4fQ.UZk3R03zs7tecCyUI33phNruBthI1SBVvUGVF5FGQS0
###
# + admin3  ---> role admin
###
POST http://127.0.0.1:8000/api/v1/users/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzI5ODg5LCJpYXQiOjE2NzIxMjAyODksImp0aSI6IjM5YjQzZTVhZjQ0OTQ3ZGJhOWZjOWNlNDg3ZTFlM2QzIiwidXNlcl9pZCI6MX0.RpJ5EbY0_vkj-09qFYVx-CCkyJT0k-TWwjOjhyP0Brc
Content-Type: application/json

{
    "username": "TestTest2",
    "email": "testtest2@test.ru"
}
###
# admin3  ---> role admin
GET http://127.0.0.1:8000/api/v1/users/TestTest2/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzI5ODg5LCJpYXQiOjE2NzIxMjAyODksImp0aSI6IjM5YjQzZTVhZjQ0OTQ3ZGJhOWZjOWNlNDg3ZTFlM2QzIiwidXNlcl9pZCI6MX0.RpJ5EbY0_vkj-09qFYVx-CCkyJT0k-TWwjOjhyP0Brc
###
# + admin3  ---> role admin
###
PATCH http://127.0.0.1:8000/api/v1/users/TestTest2/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzI5ODg5LCJpYXQiOjE2NzIxMjAyODksImp0aSI6IjM5YjQzZTVhZjQ0OTQ3ZGJhOWZjOWNlNDg3ZTFlM2QzIiwidXNlcl9pZCI6MX0.RpJ5EbY0_vkj-09qFYVx-CCkyJT0k-TWwjOjhyP0Brc
Content-Type: application/json

{
    "bio": "Привет!"
}
###
# admin3  ---> role admin
DELETE http://127.0.0.1:8000/api/v1/users/TestTest2/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzI5ODg5LCJpYXQiOjE2NzIxMjAyODksImp0aSI6IjM5YjQzZTVhZjQ0OTQ3ZGJhOWZjOWNlNDg3ZTFlM2QzIiwidXNlcl9pZCI6MX0.RpJ5EbY0_vkj-09qFYVx-CCkyJT0k-TWwjOjhyP0Brc
###
# admin5 ---> role user
GET http://127.0.0.1:8000/api/v1/users/me/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzcxNTQ5LCJpYXQiOjE2NzIxNjE5NDksImp0aSI6IjI4N2RhMDFiOWY2NzRiMDZhM2U5NDRmZTQxZDkwMjI4IiwidXNlcl9pZCI6MTA4fQ.UZk3R03zs7tecCyUI33phNruBthI1SBVvUGVF5FGQS0
###
# + admin5 ---> role user
PATCH http://127.0.0.1:8000/api/v1/users/me/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczMzcxNTQ5LCJpYXQiOjE2NzIxNjE5NDksImp0aSI6IjI4N2RhMDFiOWY2NzRiMDZhM2U5NDRmZTQxZDkwMjI4IiwidXNlcl9pZCI6MTA4fQ.UZk3R03zs7tecCyUI33phNruBthI1SBVvUGVF5FGQS0
Content-Type: application/json

{
    "bio": "Привет6"
}
###