GET http://127.0.0.1:8000/api/v1/categories/
###
GET http://127.0.0.1:8000/api/v1/genres/
###
GET http://127.0.0.1:8000/api/v1/titles/
###
GET http://127.0.0.1:8000/api/v1/titles/1/reviews/
###
GET http://127.0.0.1:8000/api/v1/titles/1/reviews/6/comments/
###
GET http://127.0.0.1:8000/api/v1/titles/1/reviews/6/comments/
###