# Generated by Django 3.2 on 2022-12-26 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Код подтверждения для API'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='Введите оценку произведения', validators=[django.core.validators.MinValueValidator(1, 'Минимальная оценка 1!'), django.core.validators.MaxValueValidator(10, 'Максимальная оценка 10!')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(help_text='Введите категорию, к которой будет относиться произведение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(help_text='Введите жанр, к которому будет относиться произведение', null=True, related_name='genres', through='reviews.GenreTitle', to='reviews.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Введите год, в котором было издано произведение', validators=[django.core.validators.MinValueValidator(1, 'Год не должен быть меньше {MIN_YEAR_TITLE}'), django.core.validators.MaxValueValidator(2022, 'Указать год из будущего не получится!')], verbose_name='Год'),
        ),
    ]
