# Generated by Django 3.2 on 2022-12-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=256, verbose_name='Наименование')),
                ('slug', models.SlugField(help_text='Введите уникальный идентификатор', unique=True, verbose_name='Уникальный slug')),
            ],
            options={
                'verbose_name': 'жанры',
                'verbose_name_plural': 'Жанры на портале',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите наименование', max_length=256, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Введите уникальный идентификатор', unique=True, verbose_name='Уникальный slug'),
        ),
    ]
