# Generated by Django 3.2 on 2022-12-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221220_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'произведению и жанру',
                'verbose_name_plural': 'Произведения и жанры на портале',
                'ordering': ('genre',),
            },
        ),
        migrations.RenameModel(
            old_name='Genry',
            new_name='Genre',
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=256, verbose_name='Наименование')),
                ('year', models.IntegerField(blank=True, help_text='Год в котором было издано произведение', verbose_name='Год')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, help_text='Категория, к которой будет относиться произведение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(blank=True, help_text='Жанр, к которому будет относиться произведение', null=True, related_name='genres', through='reviews.GenreTitle', to='reviews.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'произведению',
                'verbose_name_plural': 'Произведения на портале',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(help_text='ID жанров', on_delete=django.db.models.deletion.CASCADE, to='reviews.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(help_text='ID произведений', on_delete=django.db.models.deletion.CASCADE, to='reviews.title', verbose_name='Произведения'),
        ),
    ]
